### ISSUE TITLE
Is it necessary to install "expo-linear-gradient" package

### ISSUE THREAD

**Issue by tcf01** [LucasVeloz/react-native-dynamic-skeletons#1]
Since I have a project init from react-native-cli but not expo, when I `import { SkeletonContainer } from 'react-native-dynamic-skeletons';`, an error popped out to remind me install "expo-linear-gradient".

**Comment by LucasVeloz** [comment]
Thank you for the issue. For projects with RN CLI it's necessary to install linear gradient.

```bash
npx expo install expo-linear-gradient
```

https://docs.expo.dev/versions/latest/sdk/linear-gradient/

The doc will be updated

**Comment by tcf01** [comment]
@LucasVeloz When I install this package, it requires me to install another expo package. Can you please init a project by react-native-cli and test out?

**Comment by LucasVeloz** [comment]
I followed the steps and managed to emulate the bug. The problem exists because to run this library you need the expo-linear-gradient. A library from expo. 

When running the react native cli. You have the need to install expo modules. You can follow this steps.

```
npx install-expo-modules@latest
npx expo install expo-linear-gradient
cd ios && pod install && ..
```

If you don't wanna install expo. you can use this this library:
https://github.com/alexZajac/react-native-skeleton-content-nonexpo

I really recommend to use expo to develop react native. 
https://reactnative.dev/docs/environment-setup?guide=quickstart

The RN team recommends too.
